"""create db 7

Revision ID: cc4fd8c9c28b
Revises: b6780863208a
Create Date: 2023-07-24 12:32:11.097659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4fd8c9c28b'
down_revision = 'b6780863208a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_submenu_id_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'submenu', ['submenu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_submenu_id_fkey', 'dish', 'menu', ['submenu_id'], ['id'])
    # ### end Alembic commands ###
