"""create db 5

Revision ID: d80939900dee
Revises: 5ac2f3f5cc4b
Create Date: 2023-07-24 02:19:50.155879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80939900dee'
down_revision = '5ac2f3f5cc4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus_submenu')
    op.drop_table('submenus_dish')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submenus_dish',
    sa.Column('submenu_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dish_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], name='submenus_dish_dish_id_fkey'),
    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], name='submenus_dish_submenu_id_fkey'),
    sa.PrimaryKeyConstraint('submenu_id', 'dish_id', name='submenus_dish_pkey')
    )
    op.create_table('menus_submenu',
    sa.Column('menu_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submenu_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], name='menus_submenu_menu_id_fkey'),
    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], name='menus_submenu_submenu_id_fkey'),
    sa.PrimaryKeyConstraint('menu_id', 'submenu_id', name='menus_submenu_pkey')
    )
    # ### end Alembic commands ###
